// common Screen
export const USER_REQUEST = "USER_REQUEST";
export const USER_RESPONSE = "USER_RESPONSE";

export const LIST_REQUEST = "LIST_REQUEST";
export const LIST_RESPONSE = "LIST_RESPONSE";

export const CURRENCY_LIST_REQUEST = "CURRENCY_LIST_REQUEST";
export const CURRENCY_LIST_RESPONSE = "CURRENCY_LIST_RESPONSE";